parser: "@typescript-eslint/parser"
plugins:
- typescript
- jest
- "@typescript-eslint"
extends:
- standard
- eslint:recommended
- plugin:@typescript-eslint/recommended
- plugin:import/recommended
- plugin:import/typescript
rules:
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-unused-vars':
  - error
  - argsIgnorePattern:
      ^_
    varsIgnorePattern:
      ^_
  '@typescript-eslint/no-use-before-define': error
  '@typescript-eslint/member-delimiter-style':
  - error
  - multiline:
      delimiter: none
  import/default: error
  import/export: error
  import/named: error
  import/namespace: error
  import/newline-after-import: error
  import/no-absolute-path: error
  import/no-unresolved:
  - error
  import/no-useless-path-segments: error
  import/order:
  - error
  - newlines-between: always
    groups:
    - builtin
    - external
    - internal
    alphabetize:
      order: asc
  indent:
  - error
  - 2
  max-len:
  - error
  - code: 100
    ignoreUrls: true
    ignoreRegExpLiterals: true
    ignorePattern: "^(\
      \\} from '\\S+'|\
        from '\\S+'|\
      import .* from '\\S+'|\
      [ ]*(export )?(async )?function .*|\
      [ ]*[a-zA-Z0-9]+=\\{[^}]*\\}\
      )$"
  no-console: error
  no-use-before-define: off
  no-useless-constructor: off
