#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo "=================== Checking remote branch ======================"

# master 브랜치에 push 하지 못하도록 막는다.
FORBIDDEN_REF="refs/heads/master"
ARR_GIT_STDIN=($(echo $HUSKY_GIT_STDIN))
remote_ref=${ARR_GIT_STDIN[2]}

echo "remote_ref: $1"

if [ "$remote_ref" == "$FORBIDDEN_REF" ]
then
    echo "DO NOT PUSH it master"
    exit 1
fi

echo "=================== Checking before pushing... ======================"

# `| cat` 는 grep 으로 일치하는 내용이 없는 경우, 에러가 발생하여 본 스크립트가 종료되는 것을 막는다.
# ref: https://stackoverflow.com/a/6550543
eslint_diff_cmd='git diff --relative --name-only --diff-filter=ACMRTUXB origin/main...HEAD | grep -E "(.js$|.jsx$|.ts$|.tsx$|.json$)" | grep -v "experimental" | cat'

yarn prettier-eslint --write $(eval $eslint_diff_cmd)
changed_files=$(git diff --name-only --relative $(eval $eslint_diff_cmd))
if [ -n "${changed_files}" ]; then
  echo "Files have been reformatted. Please review changes and commit again using below command."
  echo ""
  echo "    git commit -a --amend --no-edit"
  echo ""
  echo "* Files updated:"
  echo "${changed_files[@]}"
  exit 1
fi

yarn eslint $(eval $eslint_diff_cmd)
